import React, { useState, useEffect } from "react";
import axios from "axios";

function App() {
  // Form fields
  const [description, setDescription] = useState("");
  const [title, setTitle] = useState("");
  const [tags, setTags] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [image, setImage] = useState(null);
  const [loading, setLoading] = useState(false);
  
  // For categories dropdown
  const [categories, setCategories] = useState([]);
  const [showOptional, setShowOptional] = useState(false);

  // Fetch categories for dropdown (optional)
  useEffect(() => {
    fetchCategories();
  }, []);

  const fetchCategories = async () => {
    try {
      // const response = await axios.get("https://promt-generator-dfp6.vercel.app/api/categories");
       const response = await axios.get("http://localhost:5000/api/posts");
      if (response.data.success) {
        setCategories(response.data.data);
      }
    } catch (error) {
      console.error("Error fetching categories:", error);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    // Validate required fields (description and image)
    if (!description || !image) {
      alert("Please fill in description and select an image");
      return;
    }

    try {
      setLoading(true);

      const formData = new FormData();
      
      // Required fields
      formData.append("description", description);
      formData.append("image", image);
      
      // Optional fields (only add if they have values)
      if (title) formData.append("title", title);
      if (tags) formData.append("tags", tags);
      if (categoryId) formData.append("category_id", categoryId);

      const response = await axios.post(
        "https://promt-generator-dfp6.vercel.app/api/posts",
        formData,
        {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        }
      );

      console.log("Response:", response.data);
      alert("Post uploaded successfully!");

      // Reset form
      setDescription("");
      setTitle("");
      setTags("");
      setCategoryId("");
      setImage(null);
      
      // Reset file input
      const fileInput = document.getElementById("imageInput");
      if (fileInput) fileInput.value = "";

    } catch (error) {
      console.error("Upload error:", error);
      const errorMessage = error.response?.data?.message || "Upload failed";
      alert(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <h2 style={styles.title}>📤 Upload New Post</h2>
        
        <form onSubmit={handleSubmit} style={styles.form}>
          {/* Required Fields Section */}
          <div style={styles.section}>
            <h3 style={styles.sectionTitle}>Required Fields *</h3>
            
            <div style={styles.fieldGroup}>
              <label style={styles.label}>Description *</label>
              <textarea
                placeholder="Enter description (e.g., A cyberpunk city generated by Stable Diffusion)"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                style={styles.textarea}
                rows="3"
                required
              />
            </div>

            <div style={styles.fieldGroup}>
              <label style={styles.label}>Image *</label>
              <input
                id="imageInput"
                type="file"
                accept="image/*"
                onChange={(e) => setImage(e.target.files[0])}
                style={styles.fileInput}
                required
              />
              {image && (
                <div style={styles.imagePreview}>
                  <img 
                    src={URL.createObjectURL(image)} 
                    alt="Preview" 
                    style={styles.preview}
                  />
                  <button 
                    type="button" 
                    onClick={() => setImage(null)}
                    style={styles.removeBtn}
                  >
                    Remove
                  </button>
                </div>
              )}
            </div>
          </div>

          {/* Optional Fields Toggle */}
          <button 
            type="button" 
            onClick={() => setShowOptional(!showOptional)}
            style={styles.toggleBtn}
          >
            {showOptional ? "▼ Hide Optional Fields" : "▶ Show Optional Fields"}
          </button>

          {/* Optional Fields Section */}
          {showOptional && (
            <div style={styles.section}>
              <h3 style={styles.sectionTitle}>Optional Fields</h3>
              
              <div style={styles.fieldGroup}>
                <label style={styles.label}>Title</label>
                <input
                  type="text"
                  placeholder="Enter title (e.g., Neon Cityscape)"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  style={styles.input}
                />
              </div>

              <div style={styles.fieldGroup}>
                <label style={styles.label}>Tags (comma-separated)</label>
                <input
                  type="text"
                  placeholder="e.g., cyberpunk, city, neon"
                  value={tags}
                  onChange={(e) => setTags(e.target.value)}
                  style={styles.input}
                />
                {tags && (
                  <div style={styles.tagPreview}>
                    {tags.split(",").map((tag, i) => (
                      <span key={i} style={styles.tag}>#{tag.trim()}</span>
                    ))}
                  </div>
                )}
              </div>

              <div style={styles.fieldGroup}>
                <label style={styles.label}>Category ID (Optional)</label>
                <select
                  value={categoryId}
                  onChange={(e) => setCategoryId(e.target.value)}
                  style={styles.select}
                >
                  <option value="">Select a category (optional)</option>
                  {categories.map((cat) => (
                    <option key={cat.id} value={cat.id}>
                      {cat.name}
                    </option>
                  ))}
                </select>
                {categoryId && (
                  <input
                    type="text"
                    placeholder="Or manually enter Category ID"
                    value={categoryId}
                    onChange={(e) => setCategoryId(e.target.value)}
                    style={{...styles.input, marginTop: "5px"}}
                  />
                )}
              </div>
            </div>
          )}

          <button type="submit" style={styles.button} disabled={loading}>
            {loading ? "⏳ Uploading..." : "🚀 Submit Post"}
          </button>
        </form>
      </div>
    </div>
  );
}

const styles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    padding: "20px",
  },
  card: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "30px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
    maxWidth: "600px",
    width: "100%",
  },
  title: {
    textAlign: "center",
    color: "#333",
    marginBottom: "20px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  section: {
    border: "1px solid #e0e0e0",
    borderRadius: "8px",
    padding: "15px",
    backgroundColor: "#fafafa",
  },
  sectionTitle: {
    fontSize: "16px",
    fontWeight: "bold",
    marginTop: "0",
    marginBottom: "15px",
    color: "#555",
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginBottom: "15px",
  },
  label: {
    fontWeight: "bold",
    fontSize: "14px",
    color: "#333",
  },
  input: {
    padding: "10px",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontSize: "14px",
  },
  textarea: {
    padding: "10px",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontSize: "14px",
    fontFamily: "inherit",
    resize: "vertical",
  },
  fileInput: {
    padding: "10px",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontSize: "14px",
  },
  select: {
    padding: "10px",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontSize: "14px",
    backgroundColor: "white",
  },
  imagePreview: {
    marginTop: "10px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "10px",
  },
  preview: {
    maxWidth: "200px",
    maxHeight: "200px",
    borderRadius: "8px",
    border: "1px solid #ddd",
  },
  removeBtn: {
    padding: "5px 10px",
    backgroundColor: "#dc3545",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
  },
  tagPreview: {
    display: "flex",
    flexWrap: "wrap",
    gap: "5px",
    marginTop: "5px",
  },
  tag: {
    backgroundColor: "#e0e0e0",
    padding: "3px 8px",
    borderRadius: "12px",
    fontSize: "12px",
  },
  toggleBtn: {
    backgroundColor: "#f0f0f0",
    border: "1px solid #ddd",
    padding: "8px",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
    margin: "10px 0",
  },
  button: {
    padding: "12px",
    backgroundColor: "#007bff",
    color: "white",
    border: "none",
    borderRadius: "4px",
    fontSize: "16px",
    fontWeight: "bold",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  buttonDisabled: {
    backgroundColor: "#6c757d",
    cursor: "not-allowed",
  },
};

export default App;